#!/usr/bin/env python

import sys
import gttsmap_mp
if __name__ == '__main__':
    if len(sys.argv) > 1:
        if sys.argv[1] == 'runLike':
            gttsmap_mp.cli_runLike()
        else:
            gttsmap_mp.cli()
    else:
        gttsmap_mp.cli()

